#!/bin/bash
# Bowtie script
#Params: 1.NAME 2.FOLDER

bowtie-build ${2}references/${1}.fna ${2}indexes/${1}
bowtie -S ${2}indexes/${1} ${2}reads/${1}.fastq ${2}bams/${1}.sam
samtools sort ${2}bams/${1}.sam > ${2}bams/${1}.bam

samtools index ${2}bams/${1}.bam

samtools faidx ${2}references/${1}.fna
