#!/bin/bash
# BWA script
#Params: 1.NAME 2.FOLDER 3.REFNAME 4.IS PAIRED 5.READ1 6.READ2

READLENGTH=$(awk '{if(NR%4==2) {count++; bases += length} } END{print bases/count}' "${5}" )

if [ "$READLENGTH" -gt 70 ]
then
    if [ "${4}" = "true" ]
    then
        bwa mem "${3}" "${5}" "${6}" > "${2}"bams/"${1}".sam
    else
        bwa mem "${3}" "${5}" > "${2}"bams/"${1}".sam
    fi
else
    if [ "${4}" = "true" ]
    then
        bwa aln "${3}" "${5}" > "${2}"bams/"${1}".sai; bwa aln "${3}" "${6}" > "${2}"bams/"${1}"2.sai;
        bwa samse "${3}" "${2}"bams/"${1}".sai "${2}"bams/"${1}"2.sai "${5}" "${6}" > "${2}"bams/"${1}".sam
        rm "${2}"bams/"${1}"2.sai;
    else
        bwa aln "${3}" "${5}" > "${2}"bams/"${1}".sai;
        bwa samse "${3}" "${2}"bams/"${1}".sai "${5}" > "${2}"bams/"${1}".sam
    fi
    rm "${2}"bams/"${1}".sai;
fi
