#!/bin/bash
# Bowtie script
#Params: 1.NAME 2.FOLDER 3.READS SIZE 4.EXISTING

for ((i=1; i<="${4}"; i++))
do
  rm "${2}"bams/"${1}"$i.bam
  rm "${2}"bams/"${1}"$i.bam.bai
done

if [ -z "$4" ]
then
    rm "${2}"references/"${1}".fna
    rm "${2}"references/"${1}".fna.fai
fi