#!/bin/bash
#Sam to Bam script (and indexing reference)
#Params: 1.NAME 2.FOLDER 3.BAM NUMBER 4.IS EXAMPLE

samtools sort "${2}"bams/"${1}".sam > "${2}"bams/"${1}""${3}".bam
samtools index "${2}"bams/"${1}""${3}".bam
rm "${2}"bams/"${1}".sam

if [ "${4}" = "false" ]
then
  samtools faidx "${2}"references/"${1}".fna
  rm "${2}""${1}".*.ebwt
  rm "${2}""${1}".fna.*
fi